/* Text to put at the beginning of the generated file. Probably a license. */

#ifndef _RUST_FFI_H_
#define _RUST_FFI_H_

/* Generated with cbindgen:0.13.1 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <new>

namespace rust_ffi {

extern "C" {

int32_t rust_fun(int32_t a);

} // extern "C"

} // namespace rust_ffi

#endif // _RUST_FFI_H_

/* Text to put at the end of the generated file */
